#!/bin/bash

cd dopltech/sdk
mkdir -p bin
cd bin

# Download libsdk_2.0.3_darwin_amd64.tar.gz
MAC_ARM64_ASSET=libsdk_2.0.3_darwin_amd64.tar.gz
curl -H "Authorization: token $GITHUB_TOKEN" 'https://api.github.com/repos/dopl-technologies/libsdk/releases/assets/31445834' -LJOH 'Accept: application/octet-stream'
tar -xvf $MAC_ARM64_ASSET
mv libsdk libsdk_amd64.dylib
rm $MAC_ARM64_ASSET

# # Download libsdk_2.0.3_linux_armv7.tar.gz
LINUX_ARM_ASSET=libsdk_2.0.3_linux_armv7.tar.gz
curl -H "Authorization: token $GITHUB_TOKEN" 'https://api.github.com/repos/dopl-technologies/libsdk/releases/assets/31445832' -LJOH 'Accept: application/octet-stream'
tar -xvf $LINUX_ARM_ASSET
mv libsdk libsdk_arm.so
rm $LINUX_ARM_ASSET

# # Download libsdk_2.0.3_linux_amd64.tar.gz
LINUX_AMD64_ASSET=libsdk_2.0.3_linux_amd64.tar.gz
curl -H "Authorization: token $GITHUB_TOKEN" 'https://api.github.com/repos/dopl-technologies/libsdk/releases/assets/31445836' -LJOH 'Accept: application/octet-stream'
tar -xvf $LINUX_AMD64_ASSET
mv libsdk libsdk_amd64.so
rm $LINUX_AMD64_ASSET

# # Download libsdk_2.0.3_windows_amd64.zip
WINDOWS_AMD64_ASSET=libsdk_2.0.3_windows_amd64.zip
curl -H "Authorization: token $GITHUB_TOKEN" 'https://api.github.com/repos/dopl-technologies/libsdk/releases/assets/31445835' -LJOH 'Accept: application/octet-stream'
unzip -o $WINDOWS_AMD64_ASSET
mv libsdk.dll libsdk_amd64.dll
rm $WINDOWS_AMD64_ASSET

cd -